// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: serverApi.proto

package ServerApiPkg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ServerApi service

func NewServerApiEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ServerApi service

type ServerApiService interface {
	FinAll(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type serverApiService struct {
	c    client.Client
	name string
}

func NewServerApiService(name string, c client.Client) ServerApiService {
	return &serverApiService{
		c:    c,
		name: name,
	}
}

func (c *serverApiService) FinAll(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "ServerApi.FinAll", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ServerApi service

type ServerApiHandler interface {
	FinAll(context.Context, *Request, *Response) error
}

func RegisterServerApiHandler(s server.Server, hdlr ServerApiHandler, opts ...server.HandlerOption) error {
	type serverApi interface {
		FinAll(ctx context.Context, in *Request, out *Response) error
	}
	type ServerApi struct {
		serverApi
	}
	h := &serverApiHandler{hdlr}
	return s.Handle(s.NewHandler(&ServerApi{h}, opts...))
}

type serverApiHandler struct {
	ServerApiHandler
}

func (h *serverApiHandler) FinAll(ctx context.Context, in *Request, out *Response) error {
	return h.ServerApiHandler.FinAll(ctx, in, out)
}
