// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: gateway.proto

package gateway

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Gateway service

func NewGatewayEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Gateway service

type GatewayService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Gateway_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Gateway_PingPongService, error)
}

type gatewayService struct {
	c    client.Client
	name string
}

func NewGatewayService(name string, c client.Client) GatewayService {
	return &gatewayService{
		c:    c,
		name: name,
	}
}

func (c *gatewayService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Gateway.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Gateway_StreamService, error) {
	req := c.c.NewRequest(c.name, "Gateway.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &gatewayServiceStream{stream}, nil
}

type Gateway_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type gatewayServiceStream struct {
	stream client.Stream
}

func (x *gatewayServiceStream) Close() error {
	return x.stream.Close()
}

func (x *gatewayServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gatewayServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gatewayServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gatewayServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gatewayService) PingPong(ctx context.Context, opts ...client.CallOption) (Gateway_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Gateway.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &gatewayServicePingPong{stream}, nil
}

type Gateway_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type gatewayServicePingPong struct {
	stream client.Stream
}

func (x *gatewayServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *gatewayServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *gatewayServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gatewayServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gatewayServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *gatewayServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Gateway service

type GatewayHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Gateway_StreamStream) error
	PingPong(context.Context, Gateway_PingPongStream) error
}

func RegisterGatewayHandler(s server.Server, hdlr GatewayHandler, opts ...server.HandlerOption) error {
	type gateway interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Gateway struct {
		gateway
	}
	h := &gatewayHandler{hdlr}
	return s.Handle(s.NewHandler(&Gateway{h}, opts...))
}

type gatewayHandler struct {
	GatewayHandler
}

func (h *gatewayHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.GatewayHandler.Call(ctx, in, out)
}

func (h *gatewayHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.GatewayHandler.Stream(ctx, m, &gatewayStreamStream{stream})
}

type Gateway_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type gatewayStreamStream struct {
	stream server.Stream
}

func (x *gatewayStreamStream) Close() error {
	return x.stream.Close()
}

func (x *gatewayStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gatewayStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gatewayStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gatewayStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *gatewayHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.GatewayHandler.PingPong(ctx, &gatewayPingPongStream{stream})
}

type Gateway_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type gatewayPingPongStream struct {
	stream server.Stream
}

func (x *gatewayPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *gatewayPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gatewayPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gatewayPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gatewayPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *gatewayPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
